sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456
  alioss:
    endpoint: oss-cn-shanghai.aliyuncs.com
    access-key-id: 
    access-key-secret: 
    bucket-name: sky-take-out-study-dj
  redis:
    host: localhost
    port: 6379
    password:
    database: 10

  wechat:
    appid: wx9fab0d3cd3e0c92f
    secret: 7aaaf07717db581394b991f4674d5fbc
    mchid:
    mchSerialNo:
    privateKeyFilePath:
    apiV3Key:
    weChatPayCertFilePath:
    notifyUrl: https://www.weixin.qq.com/wxpay/pay.php
    refundNotifyUrl: https://www.weixin.qq.com/wxpay/pay.php
